version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn MessageApp.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=MessageApp.settings
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: Whisper
      POSTGRES_USER: postgres  # Use the default superuser
      POSTGRES_PASSWORD: 1234  # Use the default superuser password
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
